import { google } from 'googleapis';
import nodemailer from 'nodemailer';
import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'nodejs';
type OrderInput = { customerName: string; phone: string; email: string; location: string; deliveryArea: 'valley' | 'outside'; deliveryFee: number; productName: string; quantity: number; pricePerPiece: number; totalPrice: number };
const requiredEnv = ['GOOGLE_SHEET_ID', 'GOOGLE_SERVICE_ACCOUNT_EMAIL', 'GOOGLE_PRIVATE_KEY', 'GOOGLE_SHEET_TAB_NAME', 'BUSINESS_EMAIL', 'EMAIL_FROM', 'SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASS'];
function isValid(input: Partial<OrderInput>) { return typeof input.customerName === 'string' && input.customerName.trim() && /^[0-9+\-\s]{7,20}$/.test(input.phone || '') && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.email || '') && typeof input.location === 'string' && input.location.trim() && typeof input.productName === 'string' && input.productName.trim() && Number.isInteger(input.quantity) && input.quantity >= 1 && Number.isFinite(input.pricePerPiece) && input.pricePerPiece > 0 && Number.isFinite(input.totalPrice) && input.totalPrice > 0; }
const format = (n: number) => `Rs ${n.toLocaleString('en-IN')}`;
const shell = (title: string, body: string) => `<div style="margin:0;background:#f8f2e9;padding:32px 16px;font-family:Arial,sans-serif;color:#25201d"><table role="presentation" style="max-width:620px;width:100%;margin:auto;background:#fff;border-radius:20px;overflow:hidden;border-collapse:separate"><tr><td style="padding:24px 32px;background:#25201d;color:#fff;font:700 25px Georgia,serif">Soft<span style="color:#f2c1aa">Walk</span></td></tr><tr><td style="padding:32px">${body}</td></tr><tr><td style="padding:20px 32px;background:#f8f2e9;color:#716963;font-size:12px">SoftWalk · Comfort in every step</td></tr></table></div>`;
function row(label: string, value: string | number) { return `<tr><td style="padding:10px 0;color:#716963;border-bottom:1px solid #eee">${label}</td><td style="padding:10px 0;text-align:right;font-weight:700;border-bottom:1px solid #eee">${value}</td></tr>`; }
function ownerEmail(order: OrderInput, id: string, date: string) { return shell('New order received', `<h1 style="margin:0 0 8px;font:700 30px Georgia,serif">A new order is in.</h1><p style="margin:0 0 24px;color:#716963">Order <b>${id}</b> · ${date}</p><div style="background:#fff4ee;border-radius:12px;padding:14px 16px;margin-bottom:22px;color:#8c351f"><b>Please call the customer soon to confirm this order.</b></div><h3>Customer details</h3><table style="width:100%;border-collapse:collapse">${row('Customer', order.customerName)}${row('Phone', order.phone)}${row('Email', order.email)}${row('Location', order.location)}</table><h3 style="margin-top:24px">Product details</h3><table style="width:100%;border-collapse:collapse">${row('Product', order.productName)}${row('Quantity', order.quantity)}${row('Price per piece', format(order.pricePerPiece))}${row('Total', format(order.totalPrice))}${row('Payment', 'Cash On Delivery')}${row('Status', 'New Order')}</table>`); }
function customerEmail(order: OrderInput, id: string) { const brand = process.env.BRAND_NAME || 'SoftWalk'; return shell('Order received', `<h1 style="margin:0 0 14px;font:700 30px Georgia,serif">Thank you, ${order.customerName}!</h1><p style="line-height:1.6;color:#59514c">We have received your order successfully. Our sales representative will call you soon to confirm your order.</p><div style="margin:24px 0;padding:18px;background:#f8f2e9;border-radius:12px"><b>Order ID: ${id}</b><table style="width:100%;border-collapse:collapse;margin-top:8px">${row('Product', order.productName)}${row('Quantity', order.quantity)}${row('Total', format(order.totalPrice))}${row('Payment method', 'Cash On Delivery')}</table></div><p style="color:#59514c">Questions? Reply to this email and our team will help.</p><p>Thank you,<br><b>${brand}</b></p>`); }
export async function POST(request: NextRequest) { try { const input = await request.json() as Partial<OrderInput>; if (!isValid(input)) return NextResponse.json({ error: 'Please provide complete, valid order information.' }, { status: 400 }); const missing = requiredEnv.filter(key => !process.env[key]); if (missing.length) { console.error('Missing configuration:', missing.join(', ')); return NextResponse.json({ error: 'Order service is not configured yet. Please contact us to place your order.' }, { status: 503 }); } const order = input as OrderInput; const orderId = `SW-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`; const date = new Intl.DateTimeFormat('en-NP', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Kathmandu' }).format(new Date()); const auth = new google.auth.JWT({ email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL, key: process.env.GOOGLE_PRIVATE_KEY!.replace(/\\n/g, '\n'), scopes: ['https://www.googleapis.com/auth/spreadsheets'] }); const sheets = google.sheets({ version: 'v4', auth }); const values = [[orderId, date, order.customerName, order.phone, order.email, order.location, order.productName, order.quantity, order.pricePerPiece, order.totalPrice, 'Cash On Delivery', 'New Order', '']]; await sheets.spreadsheets.values.append({ spreadsheetId: process.env.GOOGLE_SHEET_ID, range: `'${process.env.GOOGLE_SHEET_TAB_NAME!.replace(/'/g, "''")}'!A:M`, valueInputOption: 'USER_ENTERED', requestBody: { values } }); const transporter = nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT), secure: Number(process.env.SMTP_PORT) === 465, auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } }); await transporter.sendMail({ from: process.env.EMAIL_FROM, to: process.env.BUSINESS_EMAIL, replyTo: process.env.EMAIL_FROM, subject: `New Product Order Received - ${orderId}`, html: ownerEmail(order, orderId, date) }); await transporter.sendMail({ from: process.env.EMAIL_FROM, to: order.email, replyTo: process.env.EMAIL_FROM, subject: `Your Order Has Been Received - ${process.env.BRAND_NAME || 'SoftWalk'}`, html: customerEmail(order, orderId) }); return NextResponse.json({ success: true, orderId }); } catch (error) { console.error('Order submission failed:', error); return NextResponse.json({ error: 'We could not complete your order. Please try again or contact us directly.' }, { status: 500 }); } }
